# Generates src/nat.h: typed wrappers for the natives Tornado Redemption uses, with hashes
# and parameter types taken from alloc8or/rdr3-nativedb-data (research/natives.json).
import json, sys, os
here = os.path.dirname(os.path.abspath(__file__))
_cands = [os.path.join(here, '..', 'research', 'natives.json'), os.path.join(here, '..', '..', 'research', 'natives.json')]
_db = next((p for p in _cands if os.path.exists(p)), None)
if not _db:
    sys.exit('natives.json not found: put the rdr3-nativedb-data natives.json in research/ next to src/')
db = json.load(open(_db, encoding='utf-8'))
WANT = """
PLAYER_ID PLAYER_PED_ID SET_PLAYER_INVINCIBLE
DOES_ENTITY_EXIST GET_ENTITY_COORDS GET_ENTITY_HEADING GET_ENTITY_MODEL GET_ENTITY_TYPE GET_ENTITY_VELOCITY
GET_ENTITY_SPEED GET_ENTITY_ROTATION GET_ENTITY_HEIGHT_ABOVE_GROUND GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS
IS_ENTITY_ATTACHED IS_ENTITY_DEAD IS_ENTITY_A_MISSION_ENTITY IS_ENTITY_IN_AIR
SET_ENTITY_VELOCITY SET_ENTITY_COORDS_NO_OFFSET SET_ENTITY_ROTATION SET_ENTITY_VISIBLE SET_ENTITY_COLLISION
SET_ENTITY_ALPHA SET_ENTITY_DYNAMIC SET_ENTITY_HAS_GRAVITY SET_ENTITY_INVINCIBLE SET_ENTITY_AS_MISSION_ENTITY
SET_ENTITY_AS_NO_LONGER_NEEDED FREEZE_ENTITY_POSITION DELETE_ENTITY DELETE_OBJECT
APPLY_FORCE_TO_ENTITY APPLY_FORCE_TO_ENTITY_CENTER_OF_MASS ACTIVATE_PHYSICS
CREATE_MODEL_HIDE CREATE_OBJECT
IS_PED_HUMAN IS_PED_A_PLAYER IS_PED_ON_MOUNT GET_MOUNT IS_PED_IN_ANY_VEHICLE IS_PED_RAGDOLL IS_PED_FATALLY_INJURED
SET_PED_TO_RAGDOLL SET_PED_CAN_RAGDOLL KNOCK_PED_OFF_VEHICLE _IS_THIS_MODEL_A_HORSE
IS_THIS_MODEL_A_TRAIN REQUEST_MODEL HAS_MODEL_LOADED IS_MODEL_VALID IS_MODEL_IN_CDIMAGE SET_MODEL_AS_NO_LONGER_NEEDED
REQUEST_NAMED_PTFX_ASSET HAS_NAMED_PTFX_ASSET_LOADED USE_PARTICLE_FX_ASSET
START_PARTICLE_FX_LOOPED_ON_ENTITY START_PARTICLE_FX_LOOPED_AT_COORD START_PARTICLE_FX_NON_LOOPED_AT_COORD
STOP_PARTICLE_FX_LOOPED REMOVE_PARTICLE_FX DOES_PARTICLE_FX_LOOPED_EXIST
SET_PARTICLE_FX_LOOPED_SCALE SET_PARTICLE_FX_LOOPED_ALPHA SET_PARTICLE_FX_LOOPED_COLOUR SET_PARTICLE_FX_LOOPED_FAR_CLIP_DIST
SET_WEATHER_TYPE CLEAR_OVERRIDE_WEATHER CLEAR_WEATHER_TYPE_PERSIST SET_WIND_SPEED SET_WIND_DIRECTION GET_WIND_SPEED SET_RAIN
FORCE_LIGHTNING_FLASH _FORCE_LIGHTNING_FLASH_AT_COORDS GET_GROUND_Z_FOR_3D_COORD GET_HASH_KEY GET_GAME_TIMER GET_FRAME_TIME
SHAKE_GAMEPLAY_CAM STOP_GAMEPLAY_CAM_SHAKING IS_GAMEPLAY_CAM_SHAKING SET_GAMEPLAY_CAM_SHAKE_AMPLITUDE
GET_GAMEPLAY_CAM_COORD GET_GAMEPLAY_CAM_ROT
DRAW_RECT DRAW_LIGHT_WITH_RANGE GET_SCREEN_COORD_FROM_WORLD_COORD
_BG_DISPLAY_TEXT _BG_SET_TEXT_SCALE _BG_SET_TEXT_COLOR
DISABLE_ALL_CONTROL_ACTIONS SET_CLOCK_TIME PAUSE_CLOCK GET_CLOCK_HOURS SET_ENTITY_COORDS GET_MODEL_DIMENSIONS
PLACE_OBJECT_ON_GROUND_PROPERLY BLIP_ADD_FOR_COORDS SET_BLIP_COORDS SET_BLIP_SPRITE REMOVE_BLIP DOES_BLIP_EXIST SET_BLIP_SCALE _SET_BLIP_NAME
START_EXPENSIVE_SYNCHRONOUS_SHAPE_TEST_LOS_PROBE GET_SHAPE_TEST_RESULT IS_PAUSE_MENU_ACTIVE
SET_PARTICLE_FX_NON_LOOPED_COLOUR SET_PARTICLE_FX_NON_LOOPED_ALPHA
_SET_OVERRIDE_WEATHER _SET_WEATHER_TYPE_FROZEN GET_CURR_WEATHER_STATE _SET_CLOUD_HEIGHT _SET_CLOUD_POSITION _SET_CLOUD_NOISE _SET_CLOUD_LAYER
IS_ENTITY_STATIC GET_CLOCK_MINUTES HIDE_HUD_AND_RADAR_THIS_FRAME DISPLAY_RADAR TASK_SMART_FLEE_COORD IS_PED_FLEEING IS_PED_DEAD_OR_DYING
ENABLE_CONTROL_ACTION DISABLE_CONTROL_ACTION IS_DISABLED_CONTROL_PRESSED IS_USING_KEYBOARD_AND_MOUSE
SET_PARTICLE_FX_LOOPED_OFFSETS SET_ENTITY_LOD_DIST GET_ENTITY_LOD_DIST IS_PLAYER_DEAD IS_SCREEN_FADED_OUT GET_MISSION_FLAG
CREATE_CAM_WITH_PARAMS SET_CAM_ACTIVE RENDER_SCRIPT_CAMS SET_CAM_COORD POINT_CAM_AT_COORD SET_CAM_FOV DESTROY_CAM DOES_CAM_EXIST
SET_FOCUS_POS_AND_VEL CLEAR_FOCUS SHAKE_CAM IS_LOADING_SCREEN_VISIBLE
GET_ENTITY_HEALTH SET_ENTITY_CAN_BE_DAMAGED GET_PED_NEARBY_PEDS SET_ENTITY_HEALTH
CREATE_PED CREATE_VEHICLE DELETE_PED DELETE_VEHICLE SET_PED_AS_NO_LONGER_NEEDED SET_VEHICLE_AS_NO_LONGER_NEEDED
_SET_RANDOM_OUTFIT_VARIATION _EQUIP_META_PED_OUTFIT _UPDATE_PED_VARIATION _DOES_META_PED_OUTFIT_EXIST_FOR_PED_MODEL
SET_PED_RELATIONSHIP_GROUP_HASH SET_BLOCKING_OF_NON_TEMPORARY_EVENTS SET_PED_KEEP_TASK SET_PED_CONFIG_FLAG
TASK_START_SCENARIO_IN_PLACE_HASH TASK_PLAY_ANIM REQUEST_ANIM_DICT HAS_ANIM_DICT_LOADED IS_PED_USING_ANY_SCENARIO
CLEAR_PED_TASKS CLEAR_PED_TASKS_IMMEDIATELY TASK_LOOK_AT_COORD TASK_TURN_PED_TO_FACE_COORD TASK_STAND_STILL TASK_LEAVE_VEHICLE
PLAY_PED_AMBIENT_SPEECH_NATIVE _REQUEST_PED_FACIAL_MOOD_THIS_FRAME
SET_PLAYER_CONTROL SET_TIME_SCALE DO_SCREEN_FADE_IN DO_SCREEN_FADE_OUT
ANIMPOSTFX_PLAY ANIMPOSTFX_STOP SET_TIMECYCLE_MODIFIER SET_TIMECYCLE_MODIFIER_STRENGTH CLEAR_TIMECYCLE_MODIFIER DISPLAY_HUD
SET_ENTITY_HEADING SET_PED_INTO_VEHICLE IS_PED_IN_VEHICLE ATTACH_ENTITY_TO_ENTITY DETACH_ENTITY IS_ENTITY_ATTACHED_TO_ENTITY
_GET_BALLOON_OBJECT_FROM_VEHICLE _SET_BALLOON_FACE_COORD _SET_VELOCITY_FOR_BALLOON
SET_GAMEPLAY_CAM_RELATIVE_HEADING SET_GAMEPLAY_CAM_RELATIVE_PITCH GET_CAM_COORD STOP_CAM_SHAKING GET_DISABLED_CONTROL_NORMAL
DRAW_SPRITE SET_SCRIPT_GFX_DRAW_ORDER REQUEST_STREAMED_TEXTURE_DICT HAS_STREAMED_TEXTURE_DICT_LOADED
PLAY_SOUND_FRONTEND _STOP_SOUND_WITH_NAME _UI_FEED_POST_SAMPLE_TOAST _UI_FEED_POST_SAMPLE_TOAST_RIGHT
BLIP_ADD_FOR_RADIUS BLIP_ADD_MODIFIER ADD_VEG_MODIFIER_SPHERE
PIN_CLOSEST_MAP_ENTITY IS_MAP_ENTITY_PINNED _GET_PINNED_MAP_ENTITY _UNPIN_MAP_ENTITY GET_CLOSEST_OBJECT_OF_TYPE
IS_PED_SHOOTING GET_PED_LAST_WEAPON_IMPACT_COORD _GET_SADDLE_HORSE_FOR_PLAYER _GET_LAST_MOUNT
PREPARE_MUSIC_EVENT TRIGGER_MUSIC_EVENT CANCEL_MUSIC_EVENT DOES_ANIM_DICT_EXIST IS_ENTITY_IN_WATER SET_ENTITY_NO_COLLISION_ENTITY
IS_AMBIENT_SPEECH_PLAYING IS_ANY_SPEECH_PLAYING DOES_CONTEXT_EXIST_FOR_THIS_PED PLAY_PAIN IS_PED_FALLING GET_PED_RELATIONSHIP_GROUP_HASH
SET_AUDIO_FLAG TASK_WANDER_STANDARD TASK_LOOK_AT_ENTITY TASK_GO_STRAIGHT_TO_COORD GET_ENTITY_BONE_INDEX_BY_NAME GET_PED_BONE_INDEX GET_ENTITY_MAX_HEALTH
CREATE_MODEL_HIDE_EXCLUDING_SCRIPT_OBJECTS
REMOVE_ANIM_DICT GET_FINAL_RENDERED_CAM_COORD GET_FINAL_RENDERED_CAM_ROT
CREATE_NEW_SCRIPTED_CONVERSATION _IS_SCRIPTED_CONVERSATION_CREATED ADD_PED_TO_CONVERSATION START_SCRIPT_CONVERSATION
IS_SCRIPTED_CONVERSATION_PLAYING STOP_SCRIPTED_CONVERSATION CLEAR_CONVERSATION_HISTORY TEXT_BLOCK_REQUEST TEXT_BLOCK_IS_LOADED _TEXT_BLOCK_DELETE
GET_PED_BONE_COORDS _REQUEST_PED_GETUP_ANIMATION PLAY_AMBIENT_SPEECH_FROM_POSITION_NATIVE
REQUEST_IPL_HASH IS_IPL_ACTIVE_HASH REMOVE_IPL_HASH REQUEST_COLLISION_AT_COORD _HAS_COLLISION_LOADED_AT_COORD LOAD_SCENE_START_SPHERE LOAD_SCENE_STOP
GET_CLOSEST_VEHICLE_NODE_WITH_HEADING GET_WATER_HEIGHT SET_PED_ONTO_MOUNT _REMOVE_PED_FROM_MOUNT _EQUIP_META_PED_OUTFIT_PRESET
TASK_USE_NEAREST_SCENARIO_TO_COORD_WARP TASK_WANDER_IN_AREA TASK_FOLLOW_NAV_MESH_TO_COORD TASK_TURN_PED_TO_FACE_ENTITY BLIP_ADD_FOR_ENTITY
GET_CURRENT_SCRIPTED_CONVERSATION_LINE HAS_COLLISION_LOADED_AROUND_ENTITY _CLEAR_CONVERSATION_HISTORY_FOR_SCRIPTED_CONVERSATION
""".split()
TYPES = {'void':'void','int':'int','float':'float','BOOL':'BOOL','Hash':'Hash','const char*':'const char*',
         'Entity':'Entity','Ped':'Ped','Vehicle':'Vehicle','Object':'Object','Player':'Player','Any':'int',
         'Vector3':'Vector3','Vector3*':'Vector3*','float*':'float*','BOOL*':'BOOL*','Entity*':'Entity*',
         'Object*':'Object*','Ped*':'Ped*','int*':'int*','Any*':'int*','ScrHandle':'int','Cam':'int','Blip':'Blip','Blip*':'Blip*','Hash*':'Hash*','Vehicle*':'Vehicle*','Volume':'int'}
by_name = {}
for ns, fns in db.items():
    for h, f in fns.items():
        by_name[f['name']] = (ns, h, f)
out = ['// GENERATED by tools/gen_natives.py from alloc8or/rdr3-nativedb-data. Do not edit by hand.',
       '#pragma once', '#include <types.h>          // Script Hook RDR2 SDK',
       '#include <nativeCaller.h>', '']
missing = []
for name in WANT:
    if name not in by_name:
        missing.append(name); continue
    ns, h, f = by_name[name]
    ret = TYPES[f['return_type']]
    ps = [(TYPES[p['type']], p['name']) for p in f['params']]
    fn = name.lstrip('_')
    sig = ', '.join(f'{t} {n}' for t, n in ps)
    args = ''.join(f', {n}' for _, n in ps)
    rt = 'Void' if ret == 'void' else ret
    body = f'invoke<{rt}>({h}{args});' if ret == 'void' else f'return invoke<{rt}>({h}{args});'
    out.append(f'namespace {ns} {{ static inline {ret} {fn}({sig}) {{ {body} }} }}')
# REMOVE_MODEL_HIDE is documented with Any params; it mirrors CREATE_MODEL_HIDE.
out.append('namespace ENTITY { static inline void REMOVE_MODEL_HIDE(float x, float y, float z, float radius, Hash model, BOOL p5) { invoke<Void>(0x3F38A98576F6213A, x, y, z, radius, model, p5); } }')
# v1.3: play one line of a started conversation (unnamed in the DB; Rockstar calls it right after START_SCRIPT_CONVERSATION)
out.append('namespace AUDIO { static inline void PLAY_SINGLE_LINE_OF_CONVERSATION(const char* convoRoot, int lineIndex) { invoke<Void>(0x40CA665AB9D8D505, convoRoot, lineIndex); } }')
# VAR_STRING is variadic; Tornado Redemption uses the literal-string form and (v1.1) a game text label (flags 2, as Rockstar).
out.append('namespace MISC { static inline const char* VAR_STRING_LITERAL(const char* s) { return invoke<const char*>(0xFA925AC00EB830B9, 10, "LITERAL_STRING", s); } }')
out.append('namespace MISC { static inline const char* VAR_STRING_LABEL(const char* label) { return invoke<const char*>(0xFA925AC00EB830B9, 2, label); } }')
# The DB types the handle as int, but Rockstar passes it by reference (REMOVE_VEG_MODIFIER_SPHERE(&handle, 1)). A pointer is
# the safe guess: if the native wanted the value, a pointer is just a wrong handle; the other way round would crash.
out.append('namespace GRAPHICS { static inline void REMOVE_VEG_MODIFIER_SPHERE_PTR(int* handle, int p1) { invoke<Void>(0x9CF1836C03FB67A2, handle, p1); } }')
open(os.path.join(here, '..', 'src', 'nat.h'), 'w').write('\n'.join(out) + '\n')
print('generated', len(WANT) - len(missing), 'natives; missing:', missing)
# The offline harness (tools/harness) switches on native hashes: keep its table in sync with nat.h.
hs = [f'constexpr UINT64 N_{n.lstrip("_")} = {by_name[n][1]};' for n in WANT if n in by_name]
hs += ['constexpr UINT64 N_REMOVE_MODEL_HIDE = 0x3F38A98576F6213A;', 'constexpr UINT64 N_VAR_STRING_LITERAL = 0xFA925AC00EB830B9;',
       'constexpr UINT64 N_REMOVE_VEG_MODIFIER_SPHERE_PTR = 0x9CF1836C03FB67A2;', 'constexpr UINT64 N_PLAY_SINGLE_LINE_OF_CONVERSATION = 0x40CA665AB9D8D505;']
open(os.path.join(here, 'harness', 'hashes.h'), 'w').write('\n'.join(hs) + '\n')
