// GENERATED by tools/gen_natives.py from alloc8or/rdr3-nativedb-data. Do not edit by hand.
#pragma once
#include <types.h>          // Script Hook RDR2 SDK
#include <nativeCaller.h>

namespace PLAYER { static inline Player PLAYER_ID() { return invoke<Player>(0x217E9DC48139933D); } }
namespace PLAYER { static inline Ped PLAYER_PED_ID() { return invoke<Ped>(0x096275889B8E0EE0); } }
namespace PLAYER { static inline void SET_PLAYER_INVINCIBLE(Player player, BOOL toggle) { invoke<Void>(0xFEBEEBC9CBDF4B12, player, toggle); } }
namespace ENTITY { static inline BOOL DOES_ENTITY_EXIST(Entity entity) { return invoke<BOOL>(0xD42BD6EB2E0F1677, entity); } }
namespace ENTITY { static inline Vector3 GET_ENTITY_COORDS(Entity entity, BOOL alive, BOOL realCoords) { return invoke<Vector3>(0xA86D5F069399F44D, entity, alive, realCoords); } }
namespace ENTITY { static inline float GET_ENTITY_HEADING(Entity entity) { return invoke<float>(0xC230DD956E2F5507, entity); } }
namespace ENTITY { static inline Hash GET_ENTITY_MODEL(Entity entity) { return invoke<Hash>(0xDA76A9F39210D365, entity); } }
namespace ENTITY { static inline int GET_ENTITY_TYPE(Entity entity) { return invoke<int>(0x97F696ACA466B4E0, entity); } }
namespace ENTITY { static inline Vector3 GET_ENTITY_VELOCITY(Entity entity, int p1) { return invoke<Vector3>(0x4805D2B1D8CF94A9, entity, p1); } }
namespace ENTITY { static inline float GET_ENTITY_SPEED(Entity entity) { return invoke<float>(0xFB6BA510A533DF81, entity); } }
namespace ENTITY { static inline Vector3 GET_ENTITY_ROTATION(Entity entity, int rotationOrder) { return invoke<Vector3>(0xE09CAF86C32CB48F, entity, rotationOrder); } }
namespace ENTITY { static inline float GET_ENTITY_HEIGHT_ABOVE_GROUND(Entity entity) { return invoke<float>(0x0D3B5BAEA08F63E9, entity); } }
namespace ENTITY { static inline Vector3 GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(Entity entity, float offsetX, float offsetY, float offsetZ) { return invoke<Vector3>(0x1899F328B0E12848, entity, offsetX, offsetY, offsetZ); } }
namespace ENTITY { static inline BOOL IS_ENTITY_ATTACHED(Entity entity) { return invoke<BOOL>(0xEE6AD63ABF59C0B7, entity); } }
namespace ENTITY { static inline BOOL IS_ENTITY_DEAD(Entity entity) { return invoke<BOOL>(0x7D5B1F88E7504BBA, entity); } }
namespace ENTITY { static inline BOOL IS_ENTITY_A_MISSION_ENTITY(Entity entity) { return invoke<BOOL>(0x138190F64DB4BBD1, entity); } }
namespace ENTITY { static inline BOOL IS_ENTITY_IN_AIR(Entity entity, int p1) { return invoke<BOOL>(0x886E37EC497200B6, entity, p1); } }
namespace ENTITY { static inline void SET_ENTITY_VELOCITY(Entity entity, float x, float y, float z) { invoke<Void>(0x1C99BB7B6E96D16F, entity, x, y, z); } }
namespace ENTITY { static inline void SET_ENTITY_COORDS_NO_OFFSET(Entity entity, float xPos, float yPos, float zPos, BOOL xAxis, BOOL yAxis, BOOL zAxis) { invoke<Void>(0x239A3351AC1DA385, entity, xPos, yPos, zPos, xAxis, yAxis, zAxis); } }
namespace ENTITY { static inline void SET_ENTITY_ROTATION(Entity entity, float pitch, float roll, float yaw, int rotationOrder, BOOL p5) { invoke<Void>(0x9CC8314DFEDE441E, entity, pitch, roll, yaw, rotationOrder, p5); } }
namespace ENTITY { static inline void SET_ENTITY_VISIBLE(Entity entity, BOOL toggle) { invoke<Void>(0x1794B4FCC84D812F, entity, toggle); } }
namespace ENTITY { static inline void SET_ENTITY_COLLISION(Entity entity, BOOL toggle, BOOL keepPhysics) { invoke<Void>(0xF66F820909453B8C, entity, toggle, keepPhysics); } }
namespace ENTITY { static inline void SET_ENTITY_ALPHA(Entity entity, int alphaLevel, BOOL skin) { invoke<Void>(0x0DF7692B1D9E7BA7, entity, alphaLevel, skin); } }
namespace ENTITY { static inline void SET_ENTITY_DYNAMIC(Entity entity, BOOL toggle) { invoke<Void>(0xFBFC4473F66CE344, entity, toggle); } }
namespace ENTITY { static inline void SET_ENTITY_HAS_GRAVITY(Entity entity, BOOL toggle) { invoke<Void>(0x0CEDB728A1083FA7, entity, toggle); } }
namespace ENTITY { static inline void SET_ENTITY_INVINCIBLE(Entity entity, BOOL toggle) { invoke<Void>(0xA5C38736C426FCB8, entity, toggle); } }
namespace ENTITY { static inline void SET_ENTITY_AS_MISSION_ENTITY(Entity entity, BOOL scriptHostObject, BOOL grabFromOtherScript) { invoke<Void>(0xDC19C288082E586E, entity, scriptHostObject, grabFromOtherScript); } }
namespace ENTITY { static inline void SET_ENTITY_AS_NO_LONGER_NEEDED(Entity* entity) { invoke<Void>(0x4971D2F8162B9674, entity); } }
namespace ENTITY { static inline void FREEZE_ENTITY_POSITION(Entity entity, BOOL toggle) { invoke<Void>(0x7D9EFB7AD6B19754, entity, toggle); } }
namespace ENTITY { static inline void DELETE_ENTITY(Entity* entity) { invoke<Void>(0x4CD38C78BD19A497, entity); } }
namespace OBJECT { static inline void DELETE_OBJECT(Object* object) { invoke<Void>(0x931914268722C263, object); } }
namespace ENTITY { static inline void APPLY_FORCE_TO_ENTITY(Entity entity, int forceFlags, float x, float y, float z, float offX, float offY, float offZ, int boneIndex, BOOL isDirectionRel, BOOL ignoreUpVec, BOOL isForceRel, BOOL p12, BOOL p13) { invoke<Void>(0xF15E8F5D333F09C4, entity, forceFlags, x, y, z, offX, offY, offZ, boneIndex, isDirectionRel, ignoreUpVec, isForceRel, p12, p13); } }
namespace ENTITY { static inline void APPLY_FORCE_TO_ENTITY_CENTER_OF_MASS(Entity entity, int forceType, float x, float y, float z, int component, BOOL isDirectionRel, BOOL isForceRel, BOOL p8) { invoke<Void>(0x31DA7CEC5334DB37, entity, forceType, x, y, z, component, isDirectionRel, isForceRel, p8); } }
namespace PHYSICS { static inline void ACTIVATE_PHYSICS(Entity entity) { invoke<Void>(0x710311ADF0E20730, entity); } }
namespace ENTITY { static inline void CREATE_MODEL_HIDE(float x, float y, float z, float radius, Hash model, BOOL p5) { invoke<Void>(0x069848B3FB3C4426, x, y, z, radius, model, p5); } }
namespace OBJECT { static inline Object CREATE_OBJECT(Hash modelHash, float x, float y, float z, BOOL isNetwork, BOOL bScriptHostObj, BOOL dynamic, BOOL p7, BOOL p8) { return invoke<Object>(0x509D5878EB39E842, modelHash, x, y, z, isNetwork, bScriptHostObj, dynamic, p7, p8); } }
namespace PED { static inline BOOL IS_PED_HUMAN(Ped ped) { return invoke<BOOL>(0xB980061DA992779D, ped); } }
namespace PED { static inline BOOL IS_PED_A_PLAYER(Ped ped) { return invoke<BOOL>(0x12534C348C6CB68B, ped); } }
namespace PED { static inline BOOL IS_PED_ON_MOUNT(Ped ped) { return invoke<BOOL>(0x460BC76A0E10655E, ped); } }
namespace PED { static inline Ped GET_MOUNT(Ped ped) { return invoke<Ped>(0xE7E11B8DCBED1058, ped); } }
namespace PED { static inline BOOL IS_PED_IN_ANY_VEHICLE(Ped ped, BOOL atGetIn) { return invoke<BOOL>(0x997ABD671D25CA0B, ped, atGetIn); } }
namespace PED { static inline BOOL IS_PED_RAGDOLL(Ped ped) { return invoke<BOOL>(0x47E4E977581C5B55, ped); } }
namespace PED { static inline BOOL IS_PED_FATALLY_INJURED(Ped ped) { return invoke<BOOL>(0xD839450756ED5A80, ped); } }
namespace PED { static inline BOOL SET_PED_TO_RAGDOLL(Ped ped, int timeMin, int timeMax, int ragdollType, BOOL abortIfInjured, BOOL abortIfDead, const char* nmTaskMessageParameterName) { return invoke<BOOL>(0xAE99FB955581844A, ped, timeMin, timeMax, ragdollType, abortIfInjured, abortIfDead, nmTaskMessageParameterName); } }
namespace PED { static inline void SET_PED_CAN_RAGDOLL(Ped ped, BOOL toggle) { invoke<Void>(0xB128377056A54E2A, ped, toggle); } }
namespace PED { static inline void KNOCK_PED_OFF_VEHICLE(Ped ped) { invoke<Void>(0x45BBCBA77C29A841, ped); } }
namespace PED { static inline BOOL IS_THIS_MODEL_A_HORSE(Hash model) { return invoke<BOOL>(0x772A1969F649E902, model); } }
namespace VEHICLE { static inline BOOL IS_THIS_MODEL_A_TRAIN(Hash model) { return invoke<BOOL>(0xFC08C8F8C1EDF174, model); } }
namespace STREAMING { static inline void REQUEST_MODEL(Hash model, BOOL p1) { invoke<Void>(0xFA28FE3A6246FC30, model, p1); } }
namespace STREAMING { static inline BOOL HAS_MODEL_LOADED(Hash model) { return invoke<BOOL>(0x1283B8B89DD5D1B6, model); } }
namespace STREAMING { static inline BOOL IS_MODEL_VALID(Hash model) { return invoke<BOOL>(0x392C8D8E07B70EFC, model); } }
namespace STREAMING { static inline BOOL IS_MODEL_IN_CDIMAGE(Hash model) { return invoke<BOOL>(0xD6F3B6D7716CFF8E, model); } }
namespace STREAMING { static inline void SET_MODEL_AS_NO_LONGER_NEEDED(Hash model) { invoke<Void>(0x4AD96EF928BD4F9A, model); } }
namespace STREAMING { static inline void REQUEST_NAMED_PTFX_ASSET(Hash fxNameHash) { invoke<Void>(0xF2B2353BBC0D4E8F, fxNameHash); } }
namespace STREAMING { static inline BOOL HAS_NAMED_PTFX_ASSET_LOADED(Hash fxNameHash) { return invoke<BOOL>(0x65BB72F29138F5D6, fxNameHash); } }
namespace GRAPHICS { static inline void USE_PARTICLE_FX_ASSET(const char* fxName) { invoke<Void>(0xA10DB07FC234DD12, fxName); } }
namespace GRAPHICS { static inline int START_PARTICLE_FX_LOOPED_ON_ENTITY(const char* effectName, Entity entity, float xOffset, float yOffset, float zOffset, float xRot, float yRot, float zRot, float scale, BOOL xAxis, BOOL yAxis, BOOL zAxis) { return invoke<int>(0xBD41E1440CE39800, effectName, entity, xOffset, yOffset, zOffset, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis); } }
namespace GRAPHICS { static inline int START_PARTICLE_FX_LOOPED_AT_COORD(const char* effectName, float x, float y, float z, float xRot, float yRot, float zRot, float scale, BOOL xAxis, BOOL yAxis, BOOL zAxis, BOOL p11) { return invoke<int>(0xBA32867E86125D3A, effectName, x, y, z, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis, p11); } }
namespace GRAPHICS { static inline BOOL START_PARTICLE_FX_NON_LOOPED_AT_COORD(const char* effectName, float xPos, float yPos, float zPos, float xRot, float yRot, float zRot, float scale, BOOL xAxis, BOOL yAxis, BOOL zAxis) { return invoke<BOOL>(0x2E80BF72EF7C87AC, effectName, xPos, yPos, zPos, xRot, yRot, zRot, scale, xAxis, yAxis, zAxis); } }
namespace GRAPHICS { static inline void STOP_PARTICLE_FX_LOOPED(int ptfxHandle, BOOL p1) { invoke<Void>(0x22970F3A088B133B, ptfxHandle, p1); } }
namespace GRAPHICS { static inline void REMOVE_PARTICLE_FX(int ptfxHandle, BOOL p1) { invoke<Void>(0x459598F579C98929, ptfxHandle, p1); } }
namespace GRAPHICS { static inline BOOL DOES_PARTICLE_FX_LOOPED_EXIST(int ptfxHandle) { return invoke<BOOL>(0x9DD5AFF561E88F2A, ptfxHandle); } }
namespace GRAPHICS { static inline void SET_PARTICLE_FX_LOOPED_SCALE(int ptfxHandle, float scale) { invoke<Void>(0x1A9E1C0D98D093B7, ptfxHandle, scale); } }
namespace GRAPHICS { static inline void SET_PARTICLE_FX_LOOPED_ALPHA(int ptfxHandle, float alpha) { invoke<Void>(0x88786E76234F7054, ptfxHandle, alpha); } }
namespace GRAPHICS { static inline void SET_PARTICLE_FX_LOOPED_COLOUR(int ptfxHandle, float r, float g, float b, BOOL p4) { invoke<Void>(0x239879FC61C610CC, ptfxHandle, r, g, b, p4); } }
namespace GRAPHICS { static inline void SET_PARTICLE_FX_LOOPED_FAR_CLIP_DIST(int ptfxHandle, float range) { invoke<Void>(0x9B04D471DA0AD7AA, ptfxHandle, range); } }
namespace MISC { static inline void SET_WEATHER_TYPE(Hash weatherType, BOOL p1, BOOL p2, BOOL transition, float transitionTime, BOOL p5) { invoke<Void>(0x59174F1AFE095B5A, weatherType, p1, p2, transition, transitionTime, p5); } }
namespace MISC { static inline void CLEAR_OVERRIDE_WEATHER() { invoke<Void>(0x80A398F16FFE3CC3); } }
namespace MISC { static inline void CLEAR_WEATHER_TYPE_PERSIST() { invoke<Void>(0xD85DFE5C131E4AE9); } }
namespace MISC { static inline void SET_WIND_SPEED(float speed) { invoke<Void>(0xD00C2D82DC04A99F, speed); } }
namespace MISC { static inline void SET_WIND_DIRECTION(float direction) { invoke<Void>(0xB56C4F5F57A45600, direction); } }
namespace MISC { static inline float GET_WIND_SPEED() { return invoke<float>(0xFFB7E74E041150A4); } }
namespace MISC { static inline void SET_RAIN(float intensity) { invoke<Void>(0x193DFC0526830FD6, intensity); } }
namespace MISC { static inline void FORCE_LIGHTNING_FLASH() { invoke<Void>(0x369DB5B2510FA080); } }
namespace MISC { static inline void FORCE_LIGHTNING_FLASH_AT_COORDS(float x, float y, float z, float p3) { invoke<Void>(0x67943537D179597C, x, y, z, p3); } }
namespace MISC { static inline BOOL GET_GROUND_Z_FOR_3D_COORD(float x, float y, float z, float* groundZ, BOOL p4) { return invoke<BOOL>(0x24FA4267BB8D2431, x, y, z, groundZ, p4); } }
namespace MISC { static inline Hash GET_HASH_KEY(const char* string) { return invoke<Hash>(0xFD340785ADF8CFB7, string); } }
namespace MISC { static inline int GET_GAME_TIMER() { return invoke<int>(0x4F67E8ECA7D3F667); } }
namespace MISC { static inline float GET_FRAME_TIME() { return invoke<float>(0x5E72022914CE3C38); } }
namespace CAMERA { static inline void SHAKE_GAMEPLAY_CAM(const char* shakeName, float intensity) { invoke<Void>(0xD9B31B4650520529, shakeName, intensity); } }
namespace CAMERA { static inline void STOP_GAMEPLAY_CAM_SHAKING(BOOL p0) { invoke<Void>(0xE0DE43D290FB65F9, p0); } }
namespace CAMERA { static inline BOOL IS_GAMEPLAY_CAM_SHAKING() { return invoke<BOOL>(0xEA4C5F4AA0A4DBEF); } }
namespace CAMERA { static inline void SET_GAMEPLAY_CAM_SHAKE_AMPLITUDE(float amplitude) { invoke<Void>(0x570E35F5C4A44838, amplitude); } }
namespace CAMERA { static inline Vector3 GET_GAMEPLAY_CAM_COORD() { return invoke<Vector3>(0x595320200B98596E); } }
namespace CAMERA { static inline Vector3 GET_GAMEPLAY_CAM_ROT(int rotationOrder) { return invoke<Vector3>(0x0252D2B5582957A6, rotationOrder); } }
namespace GRAPHICS { static inline void DRAW_RECT(float x, float y, float width, float height, int red, int green, int blue, int alpha, BOOL p8, BOOL p9) { invoke<Void>(0x405224591DF02025, x, y, width, height, red, green, blue, alpha, p8, p9); } }
namespace GRAPHICS { static inline void DRAW_LIGHT_WITH_RANGE(float posX, float posY, float posZ, int colorR, int colorG, int colorB, float range, float intensity) { invoke<Void>(0xD2D9E04C0DF927F4, posX, posY, posZ, colorR, colorG, colorB, range, intensity); } }
namespace GRAPHICS { static inline BOOL GET_SCREEN_COORD_FROM_WORLD_COORD(float worldX, float worldY, float worldZ, float* screenX, float* screenY) { return invoke<BOOL>(0xCB50D7AFCC8B0EC6, worldX, worldY, worldZ, screenX, screenY); } }
namespace UIDEBUG { static inline void BG_DISPLAY_TEXT(const char* text, float x, float y) { invoke<Void>(0x16794E044C9EFB58, text, x, y); } }
namespace UIDEBUG { static inline void BG_SET_TEXT_SCALE(float scaleX, float scaleY) { invoke<Void>(0xA1253A3C870B6843, scaleX, scaleY); } }
namespace UIDEBUG { static inline void BG_SET_TEXT_COLOR(int red, int green, int blue, int alpha) { invoke<Void>(0x16FA5CE47F184F1E, red, green, blue, alpha); } }
namespace PAD { static inline void DISABLE_ALL_CONTROL_ACTIONS(int control) { invoke<Void>(0x5F4B6931816E599B, control); } }
namespace CLOCK { static inline void SET_CLOCK_TIME(int hour, int minute, int second) { invoke<Void>(0x3A52C59FFB2DEED8, hour, minute, second); } }
namespace CLOCK { static inline void PAUSE_CLOCK(BOOL toggle, int unused) { invoke<Void>(0x4D1A590C92BF377E, toggle, unused); } }
namespace CLOCK { static inline int GET_CLOCK_HOURS() { return invoke<int>(0xC82CF208C2B19199); } }
namespace ENTITY { static inline void SET_ENTITY_COORDS(Entity entity, float xPos, float yPos, float zPos, BOOL xAxis, BOOL yAxis, BOOL zAxis, BOOL clearArea) { invoke<Void>(0x06843DA7060A026B, entity, xPos, yPos, zPos, xAxis, yAxis, zAxis, clearArea); } }
namespace MISC { static inline void GET_MODEL_DIMENSIONS(Hash modelHash, Vector3* minimum, Vector3* maximum) { invoke<Void>(0xDCB8DDD5D054A7E7, modelHash, minimum, maximum); } }
namespace OBJECT { static inline BOOL PLACE_OBJECT_ON_GROUND_PROPERLY(Object object, BOOL p1) { return invoke<BOOL>(0x58A850EAEE20FAA3, object, p1); } }
namespace MAP { static inline Blip BLIP_ADD_FOR_COORDS(Hash blipHash, float x, float y, float z) { return invoke<Blip>(0x554D9D53F696D002, blipHash, x, y, z); } }
namespace MAP { static inline void SET_BLIP_COORDS(Blip blip, float posX, float posY, float posZ) { invoke<Void>(0x4FF674F5E23D49CE, blip, posX, posY, posZ); } }
namespace MAP { static inline void SET_BLIP_SPRITE(Blip blip, Hash hash, BOOL p2) { invoke<Void>(0x74F74D3207ED525C, blip, hash, p2); } }
namespace MAP { static inline void REMOVE_BLIP(Blip* blip) { invoke<Void>(0xF2C3C9DA47AAA54A, blip); } }
namespace MAP { static inline BOOL DOES_BLIP_EXIST(Blip blip) { return invoke<BOOL>(0xCD82FA174080B3B1, blip); } }
namespace MAP { static inline void SET_BLIP_SCALE(Blip blip, float scale) { invoke<Void>(0xD38744167B2FA257, blip, scale); } }
namespace MAP { static inline void SET_BLIP_NAME(Blip blip, const char* name) { invoke<Void>(0x9CB1A1623062F402, blip, name); } }
namespace SHAPETEST { static inline int START_EXPENSIVE_SYNCHRONOUS_SHAPE_TEST_LOS_PROBE(float x1, float y1, float z1, float x2, float y2, float z2, int flags, Entity entityToIgnore, int p8) { return invoke<int>(0x377906D8A31E5586, x1, y1, z1, x2, y2, z2, flags, entityToIgnore, p8); } }
namespace SHAPETEST { static inline int GET_SHAPE_TEST_RESULT(int shapeTestHandle, BOOL* hit, Vector3* endCoords, Vector3* surfaceNormal, Entity* entityHit) { return invoke<int>(0xEDE8AC7C5108FB1D, shapeTestHandle, hit, endCoords, surfaceNormal, entityHit); } }
namespace HUD { static inline BOOL IS_PAUSE_MENU_ACTIVE() { return invoke<BOOL>(0x535384D6067BA42E); } }
namespace GRAPHICS { static inline void SET_PARTICLE_FX_NON_LOOPED_COLOUR(float r, float g, float b) { invoke<Void>(0x60B85BED6577A35B, r, g, b); } }
namespace GRAPHICS { static inline void SET_PARTICLE_FX_NON_LOOPED_ALPHA(float alpha) { invoke<Void>(0xE8A35938A7026CEA, alpha); } }
namespace MISC { static inline void SET_OVERRIDE_WEATHER(Hash weatherType) { invoke<Void>(0xBE83CAE8ED77A94F, weatherType); } }
namespace MISC { static inline void SET_WEATHER_TYPE_FROZEN(BOOL toggle) { invoke<Void>(0xD74ACDF7DB8114AF, toggle); } }
namespace MISC { static inline void GET_CURR_WEATHER_STATE(Hash* weatherType1, Hash* weatherType2, float* percentWeather2) { invoke<Void>(0x0AC679B2342F14F2, weatherType1, weatherType2, percentWeather2); } }
namespace GRAPHICS { static inline void SET_CLOUD_HEIGHT(float height) { invoke<Void>(0xC332C91388F5580B, height); } }
namespace GRAPHICS { static inline void SET_CLOUD_POSITION(float x, float y, float z) { invoke<Void>(0x10C1767B93257480, x, y, z); } }
namespace GRAPHICS { static inline void SET_CLOUD_NOISE(float x, float y, float z) { invoke<Void>(0xFE7966DF01452F32, x, y, z); } }
namespace GRAPHICS { static inline void SET_CLOUD_LAYER(float x, float y, int p2) { invoke<Void>(0xB8C984C0D47F4F07, x, y, p2); } }
namespace ENTITY { static inline BOOL IS_ENTITY_STATIC(Entity entity) { return invoke<BOOL>(0x86468ADFA0F6B861, entity); } }
namespace CLOCK { static inline int GET_CLOCK_MINUTES() { return invoke<int>(0x4E162231B823DBBF); } }
namespace HUD { static inline void HIDE_HUD_AND_RADAR_THIS_FRAME() { invoke<Void>(0x36CDD81627A6FCD2); } }
namespace MAP { static inline void DISPLAY_RADAR(BOOL toggle) { invoke<Void>(0x1B3DA717B9AFF828, toggle); } }
namespace TASK { static inline void TASK_SMART_FLEE_COORD(Ped ped, float x, float y, float z, float distance, int time, int fleeType, float fleeSpeed) { invoke<Void>(0x94587F17E9C365D5, ped, x, y, z, distance, time, fleeType, fleeSpeed); } }
namespace PED { static inline BOOL IS_PED_FLEEING(Ped ped) { return invoke<BOOL>(0xBBCCE00B381F8482, ped); } }
namespace PED { static inline BOOL IS_PED_DEAD_OR_DYING(Ped ped, BOOL p1) { return invoke<BOOL>(0x3317DEDB88C95038, ped, p1); } }
namespace PAD { static inline void ENABLE_CONTROL_ACTION(int control, Hash action, BOOL enableRelatedActions) { invoke<Void>(0x351220255D64C155, control, action, enableRelatedActions); } }
namespace PAD { static inline void DISABLE_CONTROL_ACTION(int control, Hash action, BOOL disableRelatedActions) { invoke<Void>(0xFE99B66D079CF6BC, control, action, disableRelatedActions); } }
namespace PAD { static inline BOOL IS_DISABLED_CONTROL_PRESSED(int control, Hash action) { return invoke<BOOL>(0xE2587F8CBBD87B1D, control, action); } }
namespace PAD { static inline BOOL IS_USING_KEYBOARD_AND_MOUSE(int control) { return invoke<BOOL>(0xA571D46727E2B718, control); } }
namespace GRAPHICS { static inline void SET_PARTICLE_FX_LOOPED_OFFSETS(int ptfxHandle, float x, float y, float z, float rotX, float rotY, float rotZ) { invoke<Void>(0xD3A4A95FC94FE83B, ptfxHandle, x, y, z, rotX, rotY, rotZ); } }
namespace ENTITY { static inline void SET_ENTITY_LOD_DIST(Entity entity, int value) { invoke<Void>(0x5FB407F0A7C877BF, entity, value); } }
namespace ENTITY { static inline int GET_ENTITY_LOD_DIST(Entity entity) { return invoke<int>(0xDF240D0C2A948683, entity); } }
namespace PLAYER { static inline BOOL IS_PLAYER_DEAD(Player player) { return invoke<BOOL>(0x2E9C3FCB6798F397, player); } }
namespace CAMERA { static inline BOOL IS_SCREEN_FADED_OUT() { return invoke<BOOL>(0xF5472C80DF2FF847); } }
namespace MISC { static inline BOOL GET_MISSION_FLAG() { return invoke<BOOL>(0xB15CD1CF58771DE1); } }
namespace CAMERA { static inline int CREATE_CAM_WITH_PARAMS(const char* camName, float posX, float posY, float posZ, float rotX, float rotY, float rotZ, float fov, BOOL p8, int p9) { return invoke<int>(0x40C23491CE83708E, camName, posX, posY, posZ, rotX, rotY, rotZ, fov, p8, p9); } }
namespace CAMERA { static inline void SET_CAM_ACTIVE(int cam, BOOL active) { invoke<Void>(0x87295BCA613800C8, cam, active); } }
namespace CAMERA { static inline void RENDER_SCRIPT_CAMS(BOOL render, BOOL ease, int easeTime, BOOL p3, BOOL p4, int renderingFlags) { invoke<Void>(0x33281167E4942E4F, render, ease, easeTime, p3, p4, renderingFlags); } }
namespace CAMERA { static inline void SET_CAM_COORD(int cam, float posX, float posY, float posZ) { invoke<Void>(0xF9EE7D419EE49DE6, cam, posX, posY, posZ); } }
namespace CAMERA { static inline void POINT_CAM_AT_COORD(int cam, float x, float y, float z) { invoke<Void>(0x948B39341C3A40C2, cam, x, y, z); } }
namespace CAMERA { static inline void SET_CAM_FOV(int cam, float fieldOfView) { invoke<Void>(0x27666E5988D9D429, cam, fieldOfView); } }
namespace CAMERA { static inline void DESTROY_CAM(int cam, BOOL p1) { invoke<Void>(0x4E67E0B6D7FD5145, cam, p1); } }
namespace CAMERA { static inline BOOL DOES_CAM_EXIST(int cam) { return invoke<BOOL>(0x153AD457764FD704, cam); } }
namespace STREAMING { static inline void SET_FOCUS_POS_AND_VEL(float x, float y, float z, float offsetX, float offsetY, float offsetZ) { invoke<Void>(0x25F6EF88664540E2, x, y, z, offsetX, offsetY, offsetZ); } }
namespace STREAMING { static inline void CLEAR_FOCUS() { invoke<Void>(0x86CCAF7CE493EFBE); } }
namespace CAMERA { static inline void SHAKE_CAM(int cam, const char* type, float amplitude) { invoke<Void>(0xF9A7BCF5D050D4E7, cam, type, amplitude); } }
namespace SCRIPT { static inline BOOL IS_LOADING_SCREEN_VISIBLE() { return invoke<BOOL>(0xB54ADBE65D528FCB); } }
namespace ENTITY { static inline int GET_ENTITY_HEALTH(Entity entity) { return invoke<int>(0x82368787EA73C0F7, entity); } }
namespace ENTITY { static inline void SET_ENTITY_CAN_BE_DAMAGED(Entity entity, BOOL toggle) { invoke<Void>(0x0D06D522B90E861F, entity, toggle); } }
namespace PED { static inline int GET_PED_NEARBY_PEDS(Ped ped, int* sizeAndPeds, int ignoredPedType, int p3) { return invoke<int>(0x23F8F5FC7E8C4A6B, ped, sizeAndPeds, ignoredPedType, p3); } }
namespace ENTITY { static inline void SET_ENTITY_HEALTH(Entity entity, int healthAmount, Entity entityKilledBy) { invoke<Void>(0xAC2767ED8BDFAB15, entity, healthAmount, entityKilledBy); } }
namespace PED { static inline Ped CREATE_PED(Hash modelHash, float x, float y, float z, float heading, BOOL isNetwork, BOOL bScriptHostPed, BOOL p7, BOOL p8) { return invoke<Ped>(0xD49F9B0955C367DE, modelHash, x, y, z, heading, isNetwork, bScriptHostPed, p7, p8); } }
namespace VEHICLE { static inline Vehicle CREATE_VEHICLE(Hash modelHash, float x, float y, float z, float heading, BOOL isNetwork, BOOL bScriptHostVeh, BOOL bDontAutoCreateDraftAnimals, BOOL p8) { return invoke<Vehicle>(0xAF35D0D2583051B0, modelHash, x, y, z, heading, isNetwork, bScriptHostVeh, bDontAutoCreateDraftAnimals, p8); } }
namespace PED { static inline void DELETE_PED(Ped* ped) { invoke<Void>(0xCC0EF140F99365C5, ped); } }
namespace VEHICLE { static inline void DELETE_VEHICLE(Vehicle* vehicle) { invoke<Void>(0xE20A909D8C4A70F8, vehicle); } }
namespace ENTITY { static inline void SET_PED_AS_NO_LONGER_NEEDED(Ped* ped) { invoke<Void>(0x2595DD4236549CE3, ped); } }
namespace ENTITY { static inline void SET_VEHICLE_AS_NO_LONGER_NEEDED(Vehicle* vehicle) { invoke<Void>(0x629BFA74418D6239, vehicle); } }
namespace PED { static inline void SET_RANDOM_OUTFIT_VARIATION(Ped ped, BOOL p1) { invoke<Void>(0x283978A15512B2FE, ped, p1); } }
namespace PED { static inline void EQUIP_META_PED_OUTFIT(Ped ped, Hash hash) { invoke<Void>(0x1902C4CFCC5BE57C, ped, hash); } }
namespace PED { static inline void UPDATE_PED_VARIATION(Ped ped, BOOL p1, BOOL p2, BOOL p3, BOOL p4, BOOL p5) { invoke<Void>(0xCC8CA3E88256E58F, ped, p1, p2, p3, p4, p5); } }
namespace PED { static inline BOOL DOES_META_PED_OUTFIT_EXIST_FOR_PED_MODEL(Hash outfit, Hash model) { return invoke<BOOL>(0xC0E880B7A441164D, outfit, model); } }
namespace PED { static inline void SET_PED_RELATIONSHIP_GROUP_HASH(Ped ped, Hash relationshipGroup) { invoke<Void>(0xC80A74AC829DDD92, ped, relationshipGroup); } }
namespace PED { static inline void SET_BLOCKING_OF_NON_TEMPORARY_EVENTS(Ped ped, BOOL toggle) { invoke<Void>(0x9F8AA94D6D97DBF4, ped, toggle); } }
namespace PED { static inline void SET_PED_KEEP_TASK(Ped ped, BOOL toggle) { invoke<Void>(0x971D38760FBC02EF, ped, toggle); } }
namespace PED { static inline void SET_PED_CONFIG_FLAG(Ped ped, int flagId, BOOL value) { invoke<Void>(0x1913FE4CBF41C463, ped, flagId, value); } }
namespace TASK { static inline void TASK_START_SCENARIO_IN_PLACE_HASH(Ped ped, Hash scenarioHash, int duration, BOOL playEnterAnim, Hash conditionalHash, float heading, BOOL p6) { invoke<Void>(0x524B54361229154F, ped, scenarioHash, duration, playEnterAnim, conditionalHash, heading, p6); } }
namespace TASK { static inline void TASK_PLAY_ANIM(Ped ped, const char* animDict, const char* animName, float speed, float speedMultiplier, int duration, int flags, float playbackRate, BOOL p8, int ikFlags, BOOL p10, const char* taskFilter, BOOL p12) { invoke<Void>(0xEA47FE3719165B94, ped, animDict, animName, speed, speedMultiplier, duration, flags, playbackRate, p8, ikFlags, p10, taskFilter, p12); } }
namespace STREAMING { static inline void REQUEST_ANIM_DICT(const char* animDict) { invoke<Void>(0xA862A2AD321F94B4, animDict); } }
namespace STREAMING { static inline BOOL HAS_ANIM_DICT_LOADED(const char* animDict) { return invoke<BOOL>(0x27FF6FE8009B40CA, animDict); } }
namespace PED { static inline BOOL IS_PED_USING_ANY_SCENARIO(Ped ped) { return invoke<BOOL>(0x57AB4A3080F85143, ped); } }
namespace TASK { static inline void CLEAR_PED_TASKS(Ped ped, BOOL p1, BOOL p2) { invoke<Void>(0xE1EF3C1216AFF2CD, ped, p1, p2); } }
namespace TASK { static inline void CLEAR_PED_TASKS_IMMEDIATELY(Ped ped, BOOL p1, BOOL resetCrouch) { invoke<Void>(0xAAA34F8A7CB32098, ped, p1, resetCrouch); } }
namespace TASK { static inline void TASK_LOOK_AT_COORD(Ped ped, float x, float y, float z, int duration, int flags, int p6, BOOL p7) { invoke<Void>(0x6FA46612594F7973, ped, x, y, z, duration, flags, p6, p7); } }
namespace TASK { static inline void TASK_TURN_PED_TO_FACE_COORD(Ped ped, float x, float y, float z, int duration) { invoke<Void>(0x1DDA930A0AC38571, ped, x, y, z, duration); } }
namespace TASK { static inline void TASK_STAND_STILL(Ped ped, int time) { invoke<Void>(0x919BE13EED931959, ped, time); } }
namespace TASK { static inline void TASK_LEAVE_VEHICLE(Ped ped, Vehicle vehicle, int flags, Ped unkPed) { invoke<Void>(0xD3DBCE61A490BE02, ped, vehicle, flags, unkPed); } }
namespace AUDIO { static inline BOOL PLAY_PED_AMBIENT_SPEECH_NATIVE(Ped speaker, int* params) { return invoke<BOOL>(0x8E04FEDD28D42462, speaker, params); } }
namespace PED { static inline void REQUEST_PED_FACIAL_MOOD_THIS_FRAME(Ped ped, Hash mood, int p2) { invoke<Void>(0x8B3B71C80A29A4BB, ped, mood, p2); } }
namespace PLAYER { static inline void SET_PLAYER_CONTROL(Player player, BOOL toggle, int flags, BOOL bPreventHeadingChange) { invoke<Void>(0x4D51E59243281D80, player, toggle, flags, bPreventHeadingChange); } }
namespace MISC { static inline void SET_TIME_SCALE(float timeScale) { invoke<Void>(0x9682AF6050854856, timeScale); } }
namespace CAMERA { static inline void DO_SCREEN_FADE_IN(int duration) { invoke<Void>(0x6A053CF596F67DF7, duration); } }
namespace CAMERA { static inline void DO_SCREEN_FADE_OUT(int duration) { invoke<Void>(0x40C719A5E410B9E4, duration); } }
namespace GRAPHICS { static inline void ANIMPOSTFX_PLAY(const char* effectName) { invoke<Void>(0x4102732DF6B4005F, effectName); } }
namespace GRAPHICS { static inline void ANIMPOSTFX_STOP(const char* effectName) { invoke<Void>(0xB4FD7446BAB2F394, effectName); } }
namespace GRAPHICS { static inline void SET_TIMECYCLE_MODIFIER(const char* modifierName) { invoke<Void>(0xFA08722A5EA82DA7, modifierName); } }
namespace GRAPHICS { static inline void SET_TIMECYCLE_MODIFIER_STRENGTH(float strength) { invoke<Void>(0xFDB74C9CC54C3F37, strength); } }
namespace GRAPHICS { static inline void CLEAR_TIMECYCLE_MODIFIER() { invoke<Void>(0x0E3F4AF2D63491FB); } }
namespace HUD { static inline void DISPLAY_HUD(BOOL toggle) { invoke<Void>(0xD63FE3AF9FB3D53F, toggle); } }
namespace ENTITY { static inline void SET_ENTITY_HEADING(Entity entity, float heading) { invoke<Void>(0xCF2B9C0645C4651B, entity, heading); } }
namespace PED { static inline void SET_PED_INTO_VEHICLE(Ped ped, Vehicle vehicle, int seatIndex) { invoke<Void>(0xF75B0D629E1C063D, ped, vehicle, seatIndex); } }
namespace PED { static inline BOOL IS_PED_IN_VEHICLE(Ped ped, Vehicle vehicle, BOOL atGetIn) { return invoke<BOOL>(0xA3EE4A07279BB9DB, ped, vehicle, atGetIn); } }
namespace ENTITY { static inline void ATTACH_ENTITY_TO_ENTITY(Entity entity1, Entity entity2, int boneIndex, float xPos, float yPos, float zPos, float xRot, float yRot, float zRot, BOOL p9, BOOL useSoftPinning, BOOL collision, BOOL isPed, int vertexIndex, BOOL fixedRot, BOOL p15, BOOL p16) { invoke<Void>(0x6B9BBD38AB0796DF, entity1, entity2, boneIndex, xPos, yPos, zPos, xRot, yRot, zRot, p9, useSoftPinning, collision, isPed, vertexIndex, fixedRot, p15, p16); } }
namespace ENTITY { static inline void DETACH_ENTITY(Entity entity, BOOL p1, BOOL collision) { invoke<Void>(0x64CDE9D6BF8ECAD3, entity, p1, collision); } }
namespace ENTITY { static inline BOOL IS_ENTITY_ATTACHED_TO_ENTITY(Entity from, Entity to) { return invoke<BOOL>(0x154A3C529497053E, from, to); } }
namespace VEHICLE { static inline Entity GET_BALLOON_OBJECT_FROM_VEHICLE(Vehicle vehicle) { return invoke<Entity>(0x0BA4250D20007C2E, vehicle); } }
namespace VEHICLE { static inline void SET_BALLOON_FACE_COORD(Vehicle balloon, float x, float y, float z) { invoke<Void>(0xB42C87521D1BDD2F, balloon, x, y, z); } }
namespace VEHICLE { static inline void SET_VELOCITY_FOR_BALLOON(Vehicle balloon, float x, float y, float z) { invoke<Void>(0x12F6C6ED3EFF42DE, balloon, x, y, z); } }
namespace CAMERA { static inline void SET_GAMEPLAY_CAM_RELATIVE_HEADING(float heading, float p1) { invoke<Void>(0x5D1EB123EAC5D071, heading, p1); } }
namespace CAMERA { static inline void SET_GAMEPLAY_CAM_RELATIVE_PITCH(float x, float Value2) { invoke<Void>(0xFB760AF4F537B8BF, x, Value2); } }
namespace CAMERA { static inline Vector3 GET_CAM_COORD(int cam) { return invoke<Vector3>(0x6B12F11C2A9F0344, cam); } }
namespace CAMERA { static inline void STOP_CAM_SHAKING(int cam, BOOL p1) { invoke<Void>(0xB78CC4B4706614B0, cam, p1); } }
namespace PAD { static inline float GET_DISABLED_CONTROL_NORMAL(int control, Hash action) { return invoke<float>(0x11E65974A982637C, control, action); } }
namespace GRAPHICS { static inline void DRAW_SPRITE(const char* textureDict, const char* textureName, float screenX, float screenY, float width, float height, float heading, int red, int green, int blue, int alpha, BOOL p11) { invoke<Void>(0xC9884ECADE94CB34, textureDict, textureName, screenX, screenY, width, height, heading, red, green, blue, alpha, p11); } }
namespace GRAPHICS { static inline void SET_SCRIPT_GFX_DRAW_ORDER(int drawOrder) { invoke<Void>(0xCFCC78391C8B3814, drawOrder); } }
namespace TXD { static inline void REQUEST_STREAMED_TEXTURE_DICT(const char* textureDict, BOOL p1) { invoke<Void>(0xC1BA29DF5631B0F8, textureDict, p1); } }
namespace TXD { static inline BOOL HAS_STREAMED_TEXTURE_DICT_LOADED(const char* textureDict) { return invoke<BOOL>(0x54D6900929CCF162, textureDict); } }
namespace AUDIO { static inline void PLAY_SOUND_FRONTEND(const char* audioName, const char* audioRef, BOOL p2, int p3) { invoke<Void>(0x67C540AA08E4A6F5, audioName, audioRef, p2, p3); } }
namespace AUDIO { static inline void STOP_SOUND_WITH_NAME(const char* audioName, const char* audioRef) { invoke<Void>(0x0F2A2175734926D8, audioName, audioRef); } }
namespace UIFEED { static inline int UI_FEED_POST_SAMPLE_TOAST(int* p0, int* p1, BOOL p2, BOOL p3) { return invoke<int>(0x26E87218390E6729, p0, p1, p2, p3); } }
namespace UIFEED { static inline int UI_FEED_POST_SAMPLE_TOAST_RIGHT(int* p0, int* p1, BOOL p2) { return invoke<int>(0xB249EBCB30DD88E0, p0, p1, p2); } }
namespace MAP { static inline Blip BLIP_ADD_FOR_RADIUS(Hash blipHash, float x, float y, float z, float radius) { return invoke<Blip>(0x45F13B7E0A15C880, blipHash, x, y, z, radius); } }
namespace MAP { static inline BOOL BLIP_ADD_MODIFIER(Blip blip, Hash modifierHash) { return invoke<BOOL>(0x662D364ABF16DE2F, blip, modifierHash); } }
namespace GRAPHICS { static inline int ADD_VEG_MODIFIER_SPHERE(float x, float y, float z, float radius, int modType, int flags, int p6) { return invoke<int>(0xFA50F79257745E74, x, y, z, radius, modType, flags, p6); } }
namespace ENTITY { static inline int PIN_CLOSEST_MAP_ENTITY(Hash modelHash, float x, float y, float z, int flags) { return invoke<int>(0x6F3068258A499E52, modelHash, x, y, z, flags); } }
namespace ENTITY { static inline BOOL IS_MAP_ENTITY_PINNED(int p0) { return invoke<BOOL>(0x1FF441D7954F8709, p0); } }
namespace ENTITY { static inline Entity GET_PINNED_MAP_ENTITY(int p0) { return invoke<Entity>(0x4735E2A4BB83D9DA, p0); } }
namespace ENTITY { static inline void UNPIN_MAP_ENTITY(int pinId) { invoke<Void>(0xD2B9C78537ED5759, pinId); } }
namespace OBJECT { static inline Object GET_CLOSEST_OBJECT_OF_TYPE(float x, float y, float z, float radius, Hash modelHash, BOOL missionScriptObject, BOOL scriptHostObject, BOOL networkObject) { return invoke<Object>(0xE143FA2249364369, x, y, z, radius, modelHash, missionScriptObject, scriptHostObject, networkObject); } }
namespace PED { static inline BOOL IS_PED_SHOOTING(Ped ped) { return invoke<BOOL>(0x34616828CD07F1A1, ped); } }
namespace WEAPON { static inline BOOL GET_PED_LAST_WEAPON_IMPACT_COORD(Ped ped, Vector3* coords) { return invoke<BOOL>(0x6C4D0409BA1A2BC2, ped, coords); } }
namespace PLAYER { static inline Ped GET_SADDLE_HORSE_FOR_PLAYER(Player player) { return invoke<Ped>(0xB48050D326E9A2F3, player); } }
namespace PED { static inline Ped GET_LAST_MOUNT(Ped ped) { return invoke<Ped>(0x4C8B59171957BCF7, ped); } }
namespace AUDIO { static inline BOOL PREPARE_MUSIC_EVENT(const char* eventName) { return invoke<BOOL>(0x1E5185B72EF5158A, eventName); } }
namespace AUDIO { static inline BOOL TRIGGER_MUSIC_EVENT(const char* eventName) { return invoke<BOOL>(0x706D57B0F50DA710, eventName); } }
namespace AUDIO { static inline BOOL CANCEL_MUSIC_EVENT(const char* eventName) { return invoke<BOOL>(0x5B17A90291133DA5, eventName); } }
namespace STREAMING { static inline BOOL DOES_ANIM_DICT_EXIST(const char* animDict) { return invoke<BOOL>(0x537F44CB0D7F150D, animDict); } }
namespace ENTITY { static inline BOOL IS_ENTITY_IN_WATER(Entity entity) { return invoke<BOOL>(0xDDE5C125AC446723, entity); } }
namespace ENTITY { static inline void SET_ENTITY_NO_COLLISION_ENTITY(Entity entity1, Entity entity2, BOOL thisFrameOnly) { invoke<Void>(0xE037BF068223C38D, entity1, entity2, thisFrameOnly); } }
namespace AUDIO { static inline BOOL IS_AMBIENT_SPEECH_PLAYING(Ped ped) { return invoke<BOOL>(0x9072C8B49907BFAD, ped); } }
namespace AUDIO { static inline BOOL IS_ANY_SPEECH_PLAYING(Ped ped) { return invoke<BOOL>(0x729072355FA39EC9, ped); } }
namespace AUDIO { static inline BOOL DOES_CONTEXT_EXIST_FOR_THIS_PED(Ped ped, const char* speechName, BOOL unk) { return invoke<BOOL>(0x49B99BF3FDA89A7A, ped, speechName, unk); } }
namespace AUDIO { static inline void PLAY_PAIN(Ped ped, int painId, float p2, BOOL p3, BOOL isNetwork) { invoke<Void>(0xBC9AE166038A5CEC, ped, painId, p2, p3, isNetwork); } }
namespace PED { static inline BOOL IS_PED_FALLING(Ped ped) { return invoke<BOOL>(0xFB92A102F1C4DFA3, ped); } }
namespace PED { static inline Hash GET_PED_RELATIONSHIP_GROUP_HASH(Ped ped) { return invoke<Hash>(0x7DBDD04862D95F04, ped); } }
namespace AUDIO { static inline void SET_AUDIO_FLAG(const char* flagName, BOOL toggle) { invoke<Void>(0xB9EFD5C25018725A, flagName, toggle); } }
namespace TASK { static inline void TASK_WANDER_STANDARD(Ped ped, float p1, int p2) { invoke<Void>(0xBB9CE077274F6A1B, ped, p1, p2); } }
namespace TASK { static inline void TASK_LOOK_AT_ENTITY(Ped ped, Entity lookAtTarget, int duration, int p3, int p4, int p5) { invoke<Void>(0x69F4BE8C8CC4796C, ped, lookAtTarget, duration, p3, p4, p5); } }
namespace TASK { static inline void TASK_GO_STRAIGHT_TO_COORD(Ped ped, float x, float y, float z, float moveBlendSpeedY, int timeBeforeTeleport, float finalHeading, float targetRadius, int p8) { invoke<Void>(0xD76B57B44F1E6F8B, ped, x, y, z, moveBlendSpeedY, timeBeforeTeleport, finalHeading, targetRadius, p8); } }
namespace ENTITY { static inline int GET_ENTITY_BONE_INDEX_BY_NAME(Entity entity, const char* boneName) { return invoke<int>(0xBACA8FE9C76C124E, entity, boneName); } }
namespace PED { static inline int GET_PED_BONE_INDEX(Ped ped, int boneId) { return invoke<int>(0x3F428D08BE5AAE31, ped, boneId); } }
namespace ENTITY { static inline int GET_ENTITY_MAX_HEALTH(Entity entity, BOOL p1) { return invoke<int>(0x15D757606D170C3C, entity, p1); } }
namespace ENTITY { static inline void CREATE_MODEL_HIDE_EXCLUDING_SCRIPT_OBJECTS(float x, float y, float z, float radius, Hash model, BOOL p5) { invoke<Void>(0xD136090A9AAAB17D, x, y, z, radius, model, p5); } }
namespace STREAMING { static inline void REMOVE_ANIM_DICT(const char* animDict) { invoke<Void>(0x4763145053A33D46, animDict); } }
namespace CAMERA { static inline Vector3 GET_FINAL_RENDERED_CAM_COORD() { return invoke<Vector3>(0x5352E025EC2B416F); } }
namespace CAMERA { static inline Vector3 GET_FINAL_RENDERED_CAM_ROT(int rotationOrder) { return invoke<Vector3>(0x602685BD85DD26CA, rotationOrder); } }
namespace AUDIO { static inline BOOL CREATE_NEW_SCRIPTED_CONVERSATION(const char* convoRoot) { return invoke<BOOL>(0xD2C91A0B572AAE56, convoRoot); } }
namespace AUDIO { static inline BOOL IS_SCRIPTED_CONVERSATION_CREATED(const char* convoRoot) { return invoke<BOOL>(0xD89504D9D7D5057D, convoRoot); } }
namespace AUDIO { static inline void ADD_PED_TO_CONVERSATION(const char* convoRoot, Ped ped, const char* characterName) { invoke<Void>(0x95D9F4BC443956E7, convoRoot, ped, characterName); } }
namespace AUDIO { static inline void START_SCRIPT_CONVERSATION(const char* convoRoot, BOOL p1, BOOL p2, BOOL clone) { invoke<Void>(0x6B17C62C9635D2DC, convoRoot, p1, p2, clone); } }
namespace AUDIO { static inline BOOL IS_SCRIPTED_CONVERSATION_PLAYING(const char* p0) { return invoke<BOOL>(0x1ECC76792F661CF5, p0); } }
namespace AUDIO { static inline int STOP_SCRIPTED_CONVERSATION(const char* p0, BOOL p1, BOOL p2) { return invoke<int>(0xD79DEEFB53455EBA, p0, p1, p2); } }
namespace AUDIO { static inline void CLEAR_CONVERSATION_HISTORY() { invoke<Void>(0x33D51F801CB16E4F); } }
namespace HUD { static inline void TEXT_BLOCK_REQUEST(const char* textBlock) { invoke<Void>(0xF66090013DE648D5, textBlock); } }
namespace HUD { static inline BOOL TEXT_BLOCK_IS_LOADED(const char* textBlock) { return invoke<BOOL>(0xD0976CC34002DB57, textBlock); } }
namespace HUD { static inline void TEXT_BLOCK_DELETE(const char* textBlock) { invoke<Void>(0xAA03F130A637D923, textBlock); } }
namespace PED { static inline Vector3 GET_PED_BONE_COORDS(Ped ped, int boneId, float offsetX, float offsetY, float offsetZ) { return invoke<Vector3>(0x17C07FC640E86B4E, ped, boneId, offsetX, offsetY, offsetZ); } }
namespace PED { static inline void REQUEST_PED_GETUP_ANIMATION(Ped ped, const char* getUpType) { invoke<Void>(0xEAA8242C8479C27D, ped, getUpType); } }
namespace AUDIO { static inline BOOL PLAY_AMBIENT_SPEECH_FROM_POSITION_NATIVE(float x, float y, float z, int* params) { return invoke<BOOL>(0xED640017ED337E45, x, y, z, params); } }
namespace ENTITY { static inline void REMOVE_MODEL_HIDE(float x, float y, float z, float radius, Hash model, BOOL p5) { invoke<Void>(0x3F38A98576F6213A, x, y, z, radius, model, p5); } }
namespace AUDIO { static inline void PLAY_SINGLE_LINE_OF_CONVERSATION(const char* convoRoot, int lineIndex) { invoke<Void>(0x40CA665AB9D8D505, convoRoot, lineIndex); } }
namespace MISC { static inline const char* VAR_STRING_LITERAL(const char* s) { return invoke<const char*>(0xFA925AC00EB830B9, 10, "LITERAL_STRING", s); } }
namespace MISC { static inline const char* VAR_STRING_LABEL(const char* label) { return invoke<const char*>(0xFA925AC00EB830B9, 2, label); } }
namespace GRAPHICS { static inline void REMOVE_VEG_MODIFIER_SPHERE_PTR(int* handle, int p1) { invoke<Void>(0x9CF1836C03FB67A2, handle, p1); } }
